// Mocks generated by Mockito 5.1.0 from annotations
// in mydex/test/src/service/nav_test.dart.
// Do not manually edit this file.

import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mydex/src/core/types.dart' as _i4;
import 'package:mydex/src/service/nav.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWidget_0 extends _i1.Fake implements _i2.Widget {
  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [INav].
///
/// See the documentation for Mockito's code generation for more information.
class MockINav extends _i1.Mock implements _i3.INav {
  MockINav() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Runnable goTo(_i2.BuildContext? context, String? key) =>
      (super.noSuchMethod(Invocation.method(#goTo, [context, key]),
          returnValue: () {}) as _i4.Runnable);
  @override
  _i4.Runnable goBack(_i2.BuildContext? context) =>
      (super.noSuchMethod(Invocation.method(#goBack, [context]),
          returnValue: () {}) as _i4.Runnable);
  @override
  _i2.Widget getBy(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBy, [key]),
          returnValue: _FakeWidget_0()) as _i2.Widget);
}
