// Mocks generated by Mockito 5.1.0 from annotations
// in mydex/test/src/service/style_test.dart.
// Do not manually edit this file.

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mydex/src/service/style.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeThemeData_0 extends _i1.Fake implements _i2.ThemeData {
  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [IStyle].
///
/// See the documentation for Mockito's code generation for more information.
class MockIStyle extends _i1.Mock implements _i4.IStyle {
  MockIStyle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ThemeData darkTheme() =>
      (super.noSuchMethod(Invocation.method(#darkTheme, []),
          returnValue: _FakeThemeData_0()) as _i2.ThemeData);
  @override
  _i2.ThemeData lightTheme() =>
      (super.noSuchMethod(Invocation.method(#lightTheme, []),
          returnValue: _FakeThemeData_0()) as _i2.ThemeData);
}
