name: mydex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  async: ^2.8.2
  floor: ^1.2.0
  json_annotation: ^4.4.0
  dio: ^4.0.4
  get_it: ^7.2.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_thunk: ^0.4.0
  redux_logging: ^0.5.0
  freezed_annotation: ^1.1.0
  equatable: ^2.0.3
  get_it_mixin:
  pretty_dio_logger:
  flutter_redux_dev_tools: ^0.5.1
  redux_dev_tools: ^0.7.0
  autoequal:
  device_preview:
  flutter_screenutil: 5.3.1
  material_design_icons_flutter: 5.0.6595



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  build_test: ^2.1.5
  coverage: ^1.0.3
  mockito: ^5.1.0
  test: ^1.19.5
  floor_generator: ^1.2.0
  json_serializable: ^6.1.4
  remove_from_coverage: ^2.0.0
  test_cov: ^1.0.1
  freezed: ^1.1.0
  autoequal_gen:


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
